name: 'Azure SmartDeploy'
author: Amber Wang
description: 'Gradually deploy a new Azure container app revision with custom tests and checks at each step'
inputs:
  appName:
    description: 'Container app name.'
    required: true
  resourceGroup:
    description: 'Name of resource group.'
    required: true
  imageID:
    description: 'Container image ID for new revision deployment.'
    required: true
  revisionSuffix:
    description: 'Revision suffix for new revision.'
    required: true
  logAnalyticsWorkspace:
    description: 'Name of log analytics workspace associated with the container app. Provide for Log Analytics monitoring (recommended).'
    required: false
    default: ""
  canaryDeploy:
    description: 'Set this value to true to switch to canary deployment (monitor at StepPct, then jump to 100%). Default is linear deployment with 10% step value.'
    required: false
    default: false
  stepPct:
    description: 'Step percentage for linear deployment or canary percentage for canary deployment. Default 10%.'
    required: false
    default: 10
  stepTime:
    description: 'Time in minutes to wait before moving onto the next step of deployment. Recommended at least 5 minutes because of log lag. Default 15 minutes.'
    required: false
    default: 15
  finalPct:
    description: 'Final percentage of traffic to be routed to the new revision. Default is 100% of traffic.'
    required: false
    default: 100
  monitors:
    description: 'List of API endpoints that should be monitored.'
    required: false
    default: ""
  monitorInterval:
    description: 'Time in minutes between test runs. Default 1 minute.'
    required: false
    default: 1
  errorThreshold:
    description: 'Percentage of 500 responses (server error) that are acceptable for the new revision, ex. a value of 5 would require 95% request success to continue with deployment. Default is 0% - roll back on any 500 response .'
    required: false
    default: 0
branding:
  icon: 'box'
  color: 'blue'
runs:
  using: 'node16'
  main: 'src/main.js'
