name: 'Azure SmartDeploy'
author: Amber Wang
description: 'Gradually deploy a new Azure container app revision with custom tests and checks at each step'
inputs:
  appName:
    description: 'Container app name.'
    required: true
    default: ""
  resourceGroup:
    description: 'Name of resource group.'
    required: true
    default: ""
  imageID:
    description: 'Container image ID for new revision deployment.'
    required: false
  revisionSuffix:
    description: 'Revision suffix for new revision.'
    required: false
  canaryDeploy:
    description: 'Set this value to true to enable canary deployment (pause at a percentage, then divert the rest). Default is linear deployment with 10% step value.'
    required: false
    default: false
  stepPct:
    description: 'Step percentage for linear deployment or canary percentage for canary deployment. Default 10%.'
    required: false
    default: 10
  stepTime:
    description: 'Time in minutes to wait before moving onto the next step of deployment. Default 15 minutes.'
    required: false
    default: 15
  finalPct:
    description: 'Final percentage of traffic to be routed to the new revision. Default is 100% of traffic.'
    required: false
    default: 100
  monitoring:
    description: 'List of alarms that should be monitored.'
    required: false
  monitorInterval:
    description: 'Time in minutes between test runs. Default 1 minute.'
    required: false
    default: 1
  pretraffic-hooks:
    description: 'Validations to be run before traffic shifting.'
    required: false
  posttraffic-hooks:
    description: 'Validations to be run after traffic shifting.'
    required: false
branding:
  icon: 'box'
  color: 'blue'
runs:
  using: 'node16'
  main: 'lib/main.js'
