name: test-smartdeploy
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.head_commit.message, 'donotrun')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Smart Deploy
        uses: ./
        with:
          appName: amber-test-container
          resourceGroup: amber-test-container
          imageID: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
          revisionSuffix: test1
          stepPct: 30
          stepTime: 1
          monitorInterval: 0.5
      - name: direct traffic away
        run: az containerapp ingress traffic set -n amber-test-container -g amber-test-container --revision-weight amber-test-container--ha9tfua=100
      - name: deactivate
        run: az containerapp revision deactivate --revision amber-test-container--test1 --resource-group amber-test-container