name: test-smartdeploy
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      - run: az config set extension.use_dynamic_install=yes_without_prompt
      - name: test action
        uses: ./
      # - run: az containerapp ingress traffic set -n ${{ secrets.AZURE_APP }} -g ${{ secrets.AZURE_RG }} --revision-weight latest=10