name: test-smartdeploy
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.head_commit.message, 'donotrun')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az config set extension.use_dynamic_install=yes_without_prompt
      - name: Smart Deploy
        uses: ./
        with:
          appName: amber-test-container
          resourceGroup: amber-test-container
          imageID: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
          revisionSuffix: test1
          stepPct: 30
          stepTime: 1
          monitorInterval: 0.5