name: test-smartdeploy
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.head_commit.message, 'donotrun')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Smart Deploy
        uses: ./
        with:
          appName: error-test
          resourceGroup: amber-test-container
          imageID: ambertest.azurecr.io/testapp:3f8ddeea28c4d6bc7ad4e643ea9f6fb7eb15b714
          logAnalyticsWorkspace: amber-test-app-logs
          revisionSuffix: ${{ github.sha }}
          stepPct: 20
          stepTime: 5
          monitorInterval: 1
      # - name: direct traffic away
      #   run: az containerapp ingress traffic set -n amber-test-container -g amber-test-container --revision-weight amber-test-container--ha9tfua=100
      # - name: deactivate
      #   run: az containerapp revision deactivate --revision amber-test-container--test1 --resource-group amber-test-container
